[package]
name = "rusty-reader"
version = "0.1.0"
authors = ["Heringer <heringer@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5"
clap = "2.33"
unicode-segmentation = "1.7.1"
